language: cpp
compiler: clang
before_script:  
  - sudo apt-get update
  - sudo apt-get install graphviz
  - sudo apt-get install doxygen
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- cmake --build . --target doc
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usmart-roger:$BINTRAY_API_KEY "https://api.bintray.com/content/smart-roger/Otus_cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
  - provider: pages
    skip-cleanup: true
    github-token: $GitPages_Key  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: docs/html
    on:
      branch: master	
